import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "700"], 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog Byte | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
       <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} antialiased`}
        style={{ fontFamily: "var(--font-lexend), serif" }}
      >
        <Navbar />

        <main className={`min-h-screen max-w-7xl mx-auto px-4 xl:px-0`}>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
